FROM golang:1.17.0 as builder

WORKDIR /src

RUN go mod init example/hello

COPY hello.go /src

RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static-debian10

COPY --from=builder /go/bin/app /

ENTRYPOINT ["/app"]
